name: CI

on:
  push:
    branches: [main]

jobs:
  rust-check:
    name: Rust Check + Clippy
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ugl_am_radio/gui/src-tauri

    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.1-dev libgtk-3-dev libayatana-appindicator3-dev librsvg2-dev

      - name: Rust cache
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: ugl_am_radio/gui/src-tauri

      - name: cargo check
        run: cargo check

      - name: cargo clippy
        run: cargo clippy -- -D warnings

  build-tauri:
    name: Build (${{ matrix.os }})
    needs: rust-check
    strategy:
      matrix:
        include:
          - os: macos-latest
            target: universal-apple-darwin
          - os: windows-latest
            target: x86_64-pc-windows-msvc
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Rust cache
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: ugl_am_radio/gui/src-tauri

      - name: Install dependencies
        working-directory: ugl_am_radio/gui
        run: npm install

      - name: Build Tauri app
        working-directory: ugl_am_radio/gui
        run: npm run build

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-${{ matrix.os }}
          path: |
            ugl_am_radio/gui/src-tauri/target/release/bundle/**/*.dmg
            ugl_am_radio/gui/src-tauri/target/release/bundle/**/*.app
            ugl_am_radio/gui/src-tauri/target/release/bundle/**/*.msi
            ugl_am_radio/gui/src-tauri/target/release/bundle/**/*.exe
          retention-days: 14